sudo: required
language: go
install:
 - go get github.com/google/gopacket
 - go get github.com/google/gopacket/layers
 - go get github.com/google/gopacket/tcpassembly
 - go get github.com/google/gopacket/reassembly
 - go get github.com/google/gopacket/afpacket
script:
 - go test github.com/google/gopacket
 - go test github.com/google/gopacket/layers
 - go test github.com/google/gopacket/tcpassembly
 - go test github.com/google/gopacket/reassembly
 - go test github.com/google/gopacket/afpacket
 - ./.travis.gofmt.sh
 - ./.travis.govet.sh
 - ./.travis.golint.sh
